-- V5: File uploads tracking, admin analytics, PWA support

CREATE TABLE IF NOT EXISTS proof_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
    user_id BIGINT NOT NULL,
    file_url VARCHAR(512) NOT NULL,
    file_type VARCHAR(50),
    entity_type VARCHAR(50),
    entity_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_proof_user ON proof_uploads(user_id);
CREATE INDEX IF NOT EXISTS idx_proof_entity ON proof_uploads(entity_type, entity_id);

CREATE TABLE IF NOT EXISTS daily_active_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    user_count BIGINT NOT NULL DEFAULT 0,
    new_users BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS daily_revenue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    credits_earned BIGINT NOT NULL DEFAULT 0,
    credits_redeemed BIGINT NOT NULL DEFAULT 0,
    payouts_count INTEGER NOT NULL DEFAULT 0,
    payouts_amount NUMERIC(12,2) NOT NULL DEFAULT 0
);

ALTER TABLE payout_requests
    ADD COLUMN IF NOT EXISTS razorpay_payout_id VARCHAR(100);

INSERT INTO milestones (uuid, created_at, updated_at, name, description, milestone_type, target_value, reward_amount, is_active)
VALUES
  (gen_random_uuid()::text, NOW(), NOW(), 'First 5 Referrals', 'Refer 5 friends', 'REFERRAL_COUNT', 5, 50, true),
  (gen_random_uuid()::text, NOW(), NOW(), 'Power Referrer', 'Refer 10 friends', 'REFERRAL_COUNT', 10, 100, true),
  (gen_random_uuid()::text, NOW(), NOW(), 'Super Referrer', 'Refer 25 friends', 'REFERRAL_COUNT', 25, 250, true),
  (gen_random_uuid()::text, NOW(), NOW(), 'Referral Legend', 'Refer 50 friends', 'REFERRAL_COUNT', 50, 500, true),
  (gen_random_uuid()::text, NOW(), NOW(), 'Century Club', 'Refer 100 friends', 'REFERRAL_COUNT', 100, 1000, true)
ON CONFLICT DO NOTHING;
